### ISSUE TITLE
Define formatting standard of tickets

### ISSUE THREAD

**Issue by chrispham521** [Yams2003/Dragon-Graphics#8]
Since github has very limited tickets, let's define our standards:

Title : Example Title go here

Description: Use this current field to describe the issue

Acceptance criteria:
Unordered list of functionality necessary for this ticket.

Sizing: We will be using labels to size our tickets, these labels are "Small, Medium, and Large"

**Comment by ForgotTheColon** [comment]
Description:
Lorem ipsum

Acceptance Criteria:
- Example bullets go here
